name: Build CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Enables manual runs

jobs:
  build:
    runs-on: windows-latest  # or ubuntu-latest for Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.28.3'

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 100Line
        path: |
          build/Release/*.exe
          build/*.exe
